build:
    environment:
        php: '7.3'

    nodes:
        analysis:
            requires:
                - branch: /^master$|^(bugfix|hotfix|beta)\/.+|^feature\/[a-z]+-\d+\/(master|dev)-.+|^feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev)-.+/
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - Bundles/Propel/src/Spryker/Zed/Propel/Business/Builder/*
        - Bundles/Security/src/Spryker/Yves/Security/Plugin/Application/*
        - Bundles/*/src/Spryker/Zed/*/*Factory.php
        - Bundles/Transfer/tests/_data/test_files/*

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9.80)'
