language: php
dist: bionic

git:
  depth: 3

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader
  - npm ci

script:
  - vendor/bin/phpcs Bundles --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -p
  - npm run formatter
  - npm run mp:tslint

notifications:
  email: false
