language: php
dist: bionic

git:
    depth: 1

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - npm ci

script:
    - php -d memory_limit=1300M vendor/bin/phpcs Bundles --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -p
    - npm run formatter
    - npm run mp:tslint

notifications:
    email: false
